name: Node.js CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest
 feature/ci-workflow-coverage
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm test -- --coverage
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

 main
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
feature/ci-workflow-coverage
          path: coverage/
          retention-days: 7
          if-no-files-found: error 

          path: coverage/lcov-report
 main
